### ISSUE TITLE
Remove build_tarballs.jl?

### ISSUE THREAD

**Issue by ViralBShah** [JuliaComputing/Xyce.jl#2]
I believe the one that builds the binaries is checked into Yggdrasil. Do we need the one in this repo?

**Comment by pepijndevos** [comment]
I don't think so? I think the plan was that @Keno will hook up the binary build in the normal build process outside of Yggdrasil.

**Comment by ViralBShah** [comment]
Not sure I understand why we need to do that - but I am sure there is a good reason.
